specVersion: 1.0.0
name: evm-indexer
version: 1.0.0
runner:
  node:
    name: '@subql/node'
    version: '>=1.0.0'
  query:
    name: '@subql/query'
    version: '*'
description: >-
  This project can be used as a starting point for developing your SubQuery
  project
repository: 'https://github.com/subquery/subql-starter'
schema:
  file: ./schema.graphql
network:
  # chainId: '0xf1cf9022c7ebb34b162d5b5e34e705a5a740b2d0ecc1009fb89023e62a488108'
  # endpoint: 'wss://shiden.api.onfinality.io/public-ws#/'
  # dictionary: 'https://explorer.subquery.network/subquery/shiden-dictionary'
  chainId: '0x9eb76c5184c4ab8679d2d5d819fdf90b9c001403e9e17da2e14b6d8aec4029c6'
  endpoint: 'wss://rpc.astar.network'
  dictionary: 'https://explorer.subquery.network/subquery/astar-dictionary'
dataSources:
  - kind: substrate/FrontierEvm
    #startBlock: 393544
    startBlock: 912855
    #startBlock: 1130879
    processor:
      file: './node_modules/@subql/frontier-evm-processor/dist/index.js'
      options:
        abi: erc20
        # address: '0x0f933Dc137D21cA519ae4C7E93f87a4C8EF365Ef'
        address: '0x19574c3c8FaFc875051b665Ec131b7E60773d2C9'
        # address: '0xAeaaf0e2c81Af264101B9129C00F4440cCF0F720'
    assets:
      test:
        file: './contract/abi.json'
      erc20:
        file: './contract/abi.json'
    mapping:
      file: './dist/index.js'
      handlers:
        - handler: handleFrontierEvmCall
          kind: substrate/FrontierEvmCall
          filter:
            function: deposit()
